export const FETCH_SUBREDDITS_REQUEST = 'FETCH_SUBREDDITS_REQUEST';
export const FETCH_SUBREDDITS_SUCCESS = 'FETCH_SUBREDDITS_SUCCESS';
export const FETCH_SUBREDDITS_FAILURE = 'FETCH_SUBREDDITS_FAILURE';

export const CREATE_SUBREDDIT_REQUEST = 'CREATE_SUBREDDIT_REQUEST';
export const CREATE_SUBREDDIT_SUCCESS = 'CREATE_SUBREDDIT_SUCCESS';
export const CREATE_SUBREDDIT_FAILURE = 'CREATE_SUBREDDIT_FAILURE';

export const UPDATE_SUBREDDIT_REQUEST = 'UPDATE_SUBREDDIT_REQUEST';
export const UPDATE_SUBREDDIT_SUCCESS = 'UPDATE_SUBREDDIT_SUCCESS';
export const UPDATE_SUBREDDIT_FAILURE = 'UPDATE_SUBREDDIT_FAILURE';

export const DELETE_SUBREDDIT_REQUEST = 'DELETE_SUBREDDIT_REQUEST';
export const DELETE_SUBREDDIT_SUCCESS = 'DELETE_SUBREDDIT_SUCCESS';
export const DELETE_SUBREDDIT_FAILURE = 'DELETE_SUBREDDIT_FAILURE';
