export const FETCH_THREAD_LIST_REQUEST = 'FETCH_THREAD_LIST_REQUEST';
export const FETCH_THREAD_LIST_SUCCESS = 'FETCH_THREAD_LIST_SUCCESS';
export const FETCH_THREAD_LIST_ERROR = 'FETCH_THREAD_LIST_ERROR';
export const NOTIFICATION_THREAD_NEW = 'NOTIFICATION_THREAD_NEW';
